template: testify
packages:
  github.com/fulcrumproject/agent-lib-go/pkg/stdagent:
    config:
      filename: mocks_test.go
      dir: "{{.InterfaceDir}}"
      pkgname: "stdagent"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      FulcrumClient:
