// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stdagent

import (
	"encoding/json"

	"github.com/fulcrumproject/agent-lib-go/pkg/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFulcrumClient creates a new instance of MockFulcrumClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFulcrumClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFulcrumClient {
	mock := &MockFulcrumClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFulcrumClient is an autogenerated mock type for the FulcrumClient type
type MockFulcrumClient struct {
	mock.Mock
}

type MockFulcrumClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFulcrumClient) EXPECT() *MockFulcrumClient_Expecter {
	return &MockFulcrumClient_Expecter{mock: &_m.Mock}
}

// ClaimJob provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) ClaimJob(jobID string) error {
	ret := _mock.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_ClaimJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimJob'
type MockFulcrumClient_ClaimJob_Call struct {
	*mock.Call
}

// ClaimJob is a helper method to define mock.On call
//   - jobID string
func (_e *MockFulcrumClient_Expecter) ClaimJob(jobID interface{}) *MockFulcrumClient_ClaimJob_Call {
	return &MockFulcrumClient_ClaimJob_Call{Call: _e.mock.On("ClaimJob", jobID)}
}

func (_c *MockFulcrumClient_ClaimJob_Call) Run(run func(jobID string)) *MockFulcrumClient_ClaimJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_ClaimJob_Call) Return(err error) *MockFulcrumClient_ClaimJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_ClaimJob_Call) RunAndReturn(run func(jobID string) error) *MockFulcrumClient_ClaimJob_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteJob provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) CompleteJob(jobID string, resources any) error {
	ret := _mock.Called(jobID, resources)

	if len(ret) == 0 {
		panic("no return value specified for CompleteJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(jobID, resources)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_CompleteJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteJob'
type MockFulcrumClient_CompleteJob_Call struct {
	*mock.Call
}

// CompleteJob is a helper method to define mock.On call
//   - jobID string
//   - resources any
func (_e *MockFulcrumClient_Expecter) CompleteJob(jobID interface{}, resources interface{}) *MockFulcrumClient_CompleteJob_Call {
	return &MockFulcrumClient_CompleteJob_Call{Call: _e.mock.On("CompleteJob", jobID, resources)}
}

func (_c *MockFulcrumClient_CompleteJob_Call) Run(run func(jobID string, resources any)) *MockFulcrumClient_CompleteJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_CompleteJob_Call) Return(err error) *MockFulcrumClient_CompleteJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_CompleteJob_Call) RunAndReturn(run func(jobID string, resources any) error) *MockFulcrumClient_CompleteJob_Call {
	_c.Call.Return(run)
	return _c
}

// FailJob provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) FailJob(jobID string, errorMessage string) error {
	ret := _mock.Called(jobID, errorMessage)

	if len(ret) == 0 {
		panic("no return value specified for FailJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(jobID, errorMessage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_FailJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailJob'
type MockFulcrumClient_FailJob_Call struct {
	*mock.Call
}

// FailJob is a helper method to define mock.On call
//   - jobID string
//   - errorMessage string
func (_e *MockFulcrumClient_Expecter) FailJob(jobID interface{}, errorMessage interface{}) *MockFulcrumClient_FailJob_Call {
	return &MockFulcrumClient_FailJob_Call{Call: _e.mock.On("FailJob", jobID, errorMessage)}
}

func (_c *MockFulcrumClient_FailJob_Call) Run(run func(jobID string, errorMessage string)) *MockFulcrumClient_FailJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_FailJob_Call) Return(err error) *MockFulcrumClient_FailJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_FailJob_Call) RunAndReturn(run func(jobID string, errorMessage string) error) *MockFulcrumClient_FailJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentInfo provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) GetAgentInfo() (*agent.AgentInfo[json.RawMessage], error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAgentInfo")
	}

	var r0 *agent.AgentInfo[json.RawMessage]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*agent.AgentInfo[json.RawMessage], error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *agent.AgentInfo[json.RawMessage]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.AgentInfo[json.RawMessage])
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFulcrumClient_GetAgentInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentInfo'
type MockFulcrumClient_GetAgentInfo_Call struct {
	*mock.Call
}

// GetAgentInfo is a helper method to define mock.On call
func (_e *MockFulcrumClient_Expecter) GetAgentInfo() *MockFulcrumClient_GetAgentInfo_Call {
	return &MockFulcrumClient_GetAgentInfo_Call{Call: _e.mock.On("GetAgentInfo")}
}

func (_c *MockFulcrumClient_GetAgentInfo_Call) Run(run func()) *MockFulcrumClient_GetAgentInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFulcrumClient_GetAgentInfo_Call) Return(agentInfo *agent.AgentInfo[json.RawMessage], err error) *MockFulcrumClient_GetAgentInfo_Call {
	_c.Call.Return(agentInfo, err)
	return _c
}

func (_c *MockFulcrumClient_GetAgentInfo_Call) RunAndReturn(run func() (*agent.AgentInfo[json.RawMessage], error)) *MockFulcrumClient_GetAgentInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingJobs provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) GetPendingJobs() ([]*agent.RawJob, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPendingJobs")
	}

	var r0 []*agent.RawJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*agent.RawJob, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*agent.RawJob); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*agent.RawJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFulcrumClient_GetPendingJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingJobs'
type MockFulcrumClient_GetPendingJobs_Call struct {
	*mock.Call
}

// GetPendingJobs is a helper method to define mock.On call
func (_e *MockFulcrumClient_Expecter) GetPendingJobs() *MockFulcrumClient_GetPendingJobs_Call {
	return &MockFulcrumClient_GetPendingJobs_Call{Call: _e.mock.On("GetPendingJobs")}
}

func (_c *MockFulcrumClient_GetPendingJobs_Call) Run(run func()) *MockFulcrumClient_GetPendingJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFulcrumClient_GetPendingJobs_Call) Return(rawJobs []*agent.RawJob, err error) *MockFulcrumClient_GetPendingJobs_Call {
	_c.Call.Return(rawJobs, err)
	return _c
}

func (_c *MockFulcrumClient_GetPendingJobs_Call) RunAndReturn(run func() ([]*agent.RawJob, error)) *MockFulcrumClient_GetPendingJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) ListServices(pagination *agent.PaginationOptions) (*agent.PageResponse[*agent.RawService], error) {
	ret := _mock.Called(pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 *agent.PageResponse[*agent.RawService]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*agent.PaginationOptions) (*agent.PageResponse[*agent.RawService], error)); ok {
		return returnFunc(pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(*agent.PaginationOptions) *agent.PageResponse[*agent.RawService]); ok {
		r0 = returnFunc(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.PageResponse[*agent.RawService])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*agent.PaginationOptions) error); ok {
		r1 = returnFunc(pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFulcrumClient_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type MockFulcrumClient_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - pagination *agent.PaginationOptions
func (_e *MockFulcrumClient_Expecter) ListServices(pagination interface{}) *MockFulcrumClient_ListServices_Call {
	return &MockFulcrumClient_ListServices_Call{Call: _e.mock.On("ListServices", pagination)}
}

func (_c *MockFulcrumClient_ListServices_Call) Run(run func(pagination *agent.PaginationOptions)) *MockFulcrumClient_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *agent.PaginationOptions
		if args[0] != nil {
			arg0 = args[0].(*agent.PaginationOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_ListServices_Call) Return(pageResponse *agent.PageResponse[*agent.RawService], err error) *MockFulcrumClient_ListServices_Call {
	_c.Call.Return(pageResponse, err)
	return _c
}

func (_c *MockFulcrumClient_ListServices_Call) RunAndReturn(run func(pagination *agent.PaginationOptions) (*agent.PageResponse[*agent.RawService], error)) *MockFulcrumClient_ListServices_Call {
	_c.Call.Return(run)
	return _c
}

// ReportMetric provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) ReportMetric(metrics *agent.MetricEntry) error {
	ret := _mock.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for ReportMetric")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*agent.MetricEntry) error); ok {
		r0 = returnFunc(metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_ReportMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportMetric'
type MockFulcrumClient_ReportMetric_Call struct {
	*mock.Call
}

// ReportMetric is a helper method to define mock.On call
//   - metrics *agent.MetricEntry
func (_e *MockFulcrumClient_Expecter) ReportMetric(metrics interface{}) *MockFulcrumClient_ReportMetric_Call {
	return &MockFulcrumClient_ReportMetric_Call{Call: _e.mock.On("ReportMetric", metrics)}
}

func (_c *MockFulcrumClient_ReportMetric_Call) Run(run func(metrics *agent.MetricEntry)) *MockFulcrumClient_ReportMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *agent.MetricEntry
		if args[0] != nil {
			arg0 = args[0].(*agent.MetricEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_ReportMetric_Call) Return(err error) *MockFulcrumClient_ReportMetric_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_ReportMetric_Call) RunAndReturn(run func(metrics *agent.MetricEntry) error) *MockFulcrumClient_ReportMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UnsupportedJob provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) UnsupportedJob(jobID string, errorMessage string) error {
	ret := _mock.Called(jobID, errorMessage)

	if len(ret) == 0 {
		panic("no return value specified for UnsupportedJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(jobID, errorMessage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_UnsupportedJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsupportedJob'
type MockFulcrumClient_UnsupportedJob_Call struct {
	*mock.Call
}

// UnsupportedJob is a helper method to define mock.On call
//   - jobID string
//   - errorMessage string
func (_e *MockFulcrumClient_Expecter) UnsupportedJob(jobID interface{}, errorMessage interface{}) *MockFulcrumClient_UnsupportedJob_Call {
	return &MockFulcrumClient_UnsupportedJob_Call{Call: _e.mock.On("UnsupportedJob", jobID, errorMessage)}
}

func (_c *MockFulcrumClient_UnsupportedJob_Call) Run(run func(jobID string, errorMessage string)) *MockFulcrumClient_UnsupportedJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_UnsupportedJob_Call) Return(err error) *MockFulcrumClient_UnsupportedJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_UnsupportedJob_Call) RunAndReturn(run func(jobID string, errorMessage string) error) *MockFulcrumClient_UnsupportedJob_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAgentStatus provides a mock function for the type MockFulcrumClient
func (_mock *MockFulcrumClient) UpdateAgentStatus(status agent.AgentStatus) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAgentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(agent.AgentStatus) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFulcrumClient_UpdateAgentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAgentStatus'
type MockFulcrumClient_UpdateAgentStatus_Call struct {
	*mock.Call
}

// UpdateAgentStatus is a helper method to define mock.On call
//   - status agent.AgentStatus
func (_e *MockFulcrumClient_Expecter) UpdateAgentStatus(status interface{}) *MockFulcrumClient_UpdateAgentStatus_Call {
	return &MockFulcrumClient_UpdateAgentStatus_Call{Call: _e.mock.On("UpdateAgentStatus", status)}
}

func (_c *MockFulcrumClient_UpdateAgentStatus_Call) Run(run func(status agent.AgentStatus)) *MockFulcrumClient_UpdateAgentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 agent.AgentStatus
		if args[0] != nil {
			arg0 = args[0].(agent.AgentStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFulcrumClient_UpdateAgentStatus_Call) Return(err error) *MockFulcrumClient_UpdateAgentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFulcrumClient_UpdateAgentStatus_Call) RunAndReturn(run func(status agent.AgentStatus) error) *MockFulcrumClient_UpdateAgentStatus_Call {
	_c.Call.Return(run)
	return _c
}
